[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_calc = "4QSy8gYQMHYGCCazUAqgMqgni9Rm8YmkQASoUtMbLH7f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
